name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/frc971/bos/orin:latest
      
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -G Ninja -B build
    - name: build
      run: cmake --build build
